In [ ]:
### 1. Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.

# - Vektörler tek boyutludur . Tek array barındırır. Matrisler ise çok boyutlu ve birden fazla array barındırırlar.,


In [6]:
import numpy as np
### 2. 10 elemanli bir listeden NumPy Array’i olusturunuz.

liste = range(1,10)
array = np.array(liste)
array


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:

### 3. Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.

array = np.zeros(100).reshape(10,10)
array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:

### 4. Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.
array = np.ones(100,float).reshape(10,10)
array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
### 5.	Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.

array = np.random.randint(9,10,size = (10,10))
array

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [12]:
### 6.	5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.

array = np.arange(5,25,3)
array

array([ 5,  8, 11, 14, 17, 20, 23])

In [14]:
### 7. -1 ile 1 arasinda 30 adet Array olusturunuz.

array = np.random.randn(30)
array

array([-0.49004877, -0.62625598,  0.9659563 , -2.69242427, -1.00692054,
       -0.15735423, -1.50111204, -0.23551824, -0.77784528, -1.81540908,
        1.17307824,  0.5311917 ,  1.45611754,  0.32589151,  1.20308349,
        0.25087063,  0.61074889, -0.23677295, -0.14779271,  1.00169284,
       -0.78347704, -1.01214134, -0.26532057, -0.22843304,  0.30283781,
        2.1515139 ,  0.78512929,  1.29765269, -0.86184546,  0.35164745])

In [18]:
### 8.	0 ile 30 arasinda 5x6’lik bir matris olusturun

array = np.random.randint(0,30,size=(5,6))
array

array([[ 3, 25,  1, 21, 25,  3],
       [14,  4,  4,  0,  9,  8],
       [ 4, 26, 17,  2, 12, 28],
       [20,  2,  7, 26,  6,  0],
       [28, 25,  7,  6, 16, 24]])

In [20]:
### 9.	Kosegenleri 1 olan 10x10’luk bir matris olusturunuz.
array = np.eye(10)
array

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [27]:
### 10. 0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;
"""* a. eleman sayisini 
* b. boyut bilgisini/sayisini 
* c. satir X sutun bilgisini 
* d. veri tipini numpy metodlariyla yazdiriniz."""
array = np.random.randint(1,11,size=(5,10))
array.size
array.ndim
array.shape
array.dtype

dtype('int32')

In [34]:
### 11. 0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak)

array = (np.random.randint(10,size=(3,4,7)))
array

array([[[9, 9, 9, 7, 6, 3, 6],
        [7, 6, 7, 0, 0, 4, 6],
        [9, 6, 8, 2, 1, 6, 5],
        [4, 4, 9, 1, 0, 4, 0]],

       [[5, 5, 2, 4, 8, 3, 3],
        [6, 4, 5, 3, 6, 1, 9],
        [6, 2, 7, 7, 5, 9, 6],
        [8, 8, 8, 3, 5, 8, 2]],

       [[6, 8, 1, 2, 7, 8, 4],
        [4, 2, 2, 2, 0, 7, 1],
        [3, 7, 8, 3, 9, 6, 5],
        [4, 3, 2, 1, 5, 8, 2]]])

In [39]:
### 12. Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)

vektor = np.random.randint(1,25,9)
vektor.reshape(3,3)

array([[11, 20, 23],
       [11, 24, 13],
       [ 5, 10, 17]])

In [40]:
### 13. 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.
vektor1 = np.random.randint(1,15,5)
vektor2 = np.random.randint(1,15,5)
vektor3 = np.random.randint(1,15,5)
vektor4 = np.random.randint(1,15,5)

vektor1+vektor2+vektor3+vektor4

array([29, 32, 23, 36, 39])

In [48]:
### 14. 2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,
vektor1 = np.random.randint(1,15,4).reshape(2,2)
vektor2 = np.random.randint(1,15,4).reshape(2,2)

np.hstack([vektor1,vektor2])


array([[ 3,  2, 14, 13],
       [14,  8,  9,  9]])

In [ ]:
### 15. Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?
# axis 1 kolonlardır 0 ise satır bazlı işlem yaptırır.


In [59]:
### 16. Farkli boyutlardaki arraylari satir ve sutun bazli ayri ayri birlestiriniz.
vektor1 = np.random.randint(1,15,4).reshape(2,2)
vektor2 = np.random.randint(1,15,6).reshape(3,2)
print(vektor1)
print(vektor2)

[[ 5 11]
 [ 4  5]]
[[ 6  2]
 [14  8]
 [13  4]]


In [60]:
np.concatenate([vektor1,vektor2],axis = 0)

array([[ 5, 11],
       [ 4,  5],
       [ 6,  2],
       [14,  8],
       [13,  4]])

In [63]:
vektor1 = np.random.randint(1,15,9).reshape(3,3)
vektor2 = np.random.randint(1,15,6).reshape(3,2)
print(vektor1)
print(vektor2)

[[10  4  6]
 [ 1  9 10]
 [ 7  3 11]]
[[12  7]
 [ 1  3]
 [ 3 11]]


In [65]:
np.concatenate([vektor1,vektor2],axis = 1)

array([[10,  4,  6, 12,  7],
       [ 1,  9, 10,  1,  3],
       [ 7,  3, 11,  3, 11]])

In [70]:
### 17. 10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 4 ayri array olusturunuz.

array = np.arange(1,11)
np.split(array,[1,2,3])

[array([1]), array([2]), array([3]), array([ 4,  5,  6,  7,  8,  9, 10])]

In [75]:
### 18. Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz. 
# Sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.

array = np.random.randint(1,20,10)
array.sort()
print(array.argsort(),array)


[0 1 2 3 4 5 6 7 8 9] [ 3  3  6  6 10 11 13 13 17 19]


In [80]:
### 19. 20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.

array = np.random.randint(500,size=(20))
print(array[3])
print(array[5])
print(array[7])

140
42
369


In [81]:
### 20. 10 elemanli random bir vektor olusturunuz ve bu arrayin 4. elemanini farkli bir sayiyla degistiriniz.
print(array[4])
array[4]= 100
print(array[4])

384
100


In [ ]:

### 21. “Diagonal Matrix” ve “Trace Matrix” kavramlari hakkinda bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.
# 'dioganal' = 'köşegenler hariç her yer 0 olan matrixler.'
# trace matrix = sol üst köşegenden sağ alt köşegene uzanan sayıların toplamıdır.


In [95]:
### 22. 5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)
array = np.arange(1,26).reshape(5,5)
print(array)
diagonal = np.diag(np.diag(array))
diagonal

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 1,  0,  0,  0,  0],
       [ 0,  7,  0,  0,  0],
       [ 0,  0, 13,  0,  0],
       [ 0,  0,  0, 19,  0],
       [ 0,  0,  0,  0, 25]])

In [99]:
diagonal[0,0]
for i in range(len(diagonal/5)):
    print(diagonal[i,i])


1
7
13
19
25


In [100]:
### 24. 10X10 luk bir matris olusturunuz ve 3.satirin 5.sutununa ulasiniz. Ayrica;
"""* a. 5.sutunun tum satirlarina ulasiniz. 
* b. Tum sutunlarin 2.satirlarina ulasiniz. 
* c. tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz. 
* d. satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz. 
* e. satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz. 
* f. sutun indexi sadece 3, 6,9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz. 
* g. 5. indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz."""

array = np.random.randint(101,size=(10,10))
array

array([[  8,  35,  98,  83,  14,  75,  61,   6,  33,  51],
       [ 17,  76,  46, 100,   1,  14,  15,  33,  29,  31],
       [ 65,  55,  16,  42,  69,  82,  65,  60,  59,  72],
       [ 94,  23,  92,  62,  45,  22,  49,  15,  19,   0],
       [ 25,  40,  44,  92,  23,  90,  39,  38,  12,  19],
       [ 90,  26,  83,  96,  55,  80,   3,  77,  65, 100],
       [  0,  59,  37,  61,  75,  79,  73,   6,  76,  48],
       [ 69,  49,  74,  89,  14,  57,  82,  47,  20,  21],
       [ 73,  24,  82,  45,  19,  73,   6,  31,  83,  79],
       [ 11,   6,  98,  30,  13,  44,  36,  18,  71,   2]])

In [101]:
array[:,5]

array([75, 14, 82, 22, 90, 80, 79, 57, 73, 44])

In [104]:
array[1,:]

array([ 17,  76,  46, 100,   1,  14,  15,  33,  29,  31])

In [105]:
array[2:7,:]

array([[ 65,  55,  16,  42,  69,  82,  65,  60,  59,  72],
       [ 94,  23,  92,  62,  45,  22,  49,  15,  19,   0],
       [ 25,  40,  44,  92,  23,  90,  39,  38,  12,  19],
       [ 90,  26,  83,  96,  55,  80,   3,  77,  65, 100],
       [  0,  59,  37,  61,  75,  79,  73,   6,  76,  48]])

In [106]:
array[2:5,3:7]

array([[42, 69, 82, 65],
       [62, 45, 22, 49],
       [92, 23, 90, 39]])

In [107]:
### 25. 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz (tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;

"""* a. 20 den buyuk olan kac deger var. 
* b. 30’dan kucuk kac deger var 
* c. icerisinde 33 gecen kac deger var 
* d. olusturulan arrayin tum elemanlarini 5 ile carpin. 
* e. olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz."""

array = np.arange(0,50,5)

In [111]:
array[array > 20] 

array([25, 30, 35, 40, 45])

In [112]:
array < 30 

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

In [113]:
array *5  

array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225])

In [114]:
array % 2 

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [126]:
### 26. 0 ile 1 arasinda 50 elamanli bir array olusturunuz ve ortalamasini aliniz. Ayrica;
"""* a. standart sapmasini aliniz. 
* b. varyansini aliniz. 
* c. median’ini aliniz. 
* d. en kucuk degeri bulunuz. 
* e. en buyuk degeri bulunuz."""
print(array)
print(array.mean())
print(np.var(array))
print(np.median(array))
print(np.min(array))
print(np.max(array))

[ 0  5 10 15 20 25 30 35 40 45]
22.5
206.25
22.5
0
45


In [ ]:
### 27.	Pandas seriler ve numpy arrayler arasindaki farklar nelerdir yaziniz.
'birinde index vardır birinde yoktur.'

In [1]:
import pandas as pd
### 28.	Indexi buyuk harflerden olusan, icinde farkli veri tipleri bulunan 5 elemanli bir seri olusturunuz.
seri = pd.Series([1,2,3,4,5],['A','B','C','D','E'])
seri


A    1
B    2
C    3
D    4
E    5
dtype: int64

In [4]:

### 29.	Key’ler ulke adlari, value’lar baskentleri olacak sekilde 5 elemanli bir sozluk olusturup onu seriye ceviriniz. (ornek: fransa:paris)

sozluk = {'Türkiye':'Ankara','Hollanda':'Amsterdam','Amerika':'Washington','Fransa':'Paris','Almanya':'Berlin'}
seri = pd.Series(sozluk)
seri

Türkiye         Ankara
Hollanda     Amsterdam
Amerika     Washington
Fransa           Paris
Almanya         Berlin
dtype: object

In [25]:
### 30.	10 elemanli random bir vektor olusturun.
"""* Vektoru seriye cevirip indexleri str olarak belirleyin. 
(ornek: a,b,c,d,e,f,g.. seklinde)
* Index ismine gore serinin 3. elemanina ulasin. 
(ornek: c indexine karsilik gelen deger)
* Serinin index sirasina gore 1. Elamanina ulasin.
* Index ismine gore serinin  2. Ve 7. Elemanlarina ayni anda ulasin. 
(Ornek: b ve g indexine karsilik gelen degerler)
* Index ismi ile serinin 2. Ve 7. Elemanlari arasindaki degerleri yazdirin.
(Ornek: b,c,d,e,f,g indexlerine karsilik gelen degerler)
* Index sirasiyla serinin 4. indexinden son indexine kadar olan degerleri yazdirin.

"""

vektor = np.array(['a','b','c','d','e','f','g','h','i','m'])
seri = pd.Series(range(1,11),index=(vektor),dtype=str)
seri

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
m    10
dtype: object

In [26]:
seri.loc['c']

'3'

In [32]:
seri.loc[['b','g']]

b    2
g    7
dtype: object

In [29]:
seri.loc['b':'g']

b    2
c    3
d    4
e    5
f    6
g    7
dtype: object

In [33]:
seri.iloc[4:]

e     5
f     6
g     7
h     8
i     9
m    10
dtype: object

In [37]:
### 31.	2 adet 5 elemanli seri olusturun.
"""* Olusturdugunuz serileri birlestirin.
* Birlesen 10 elemanli serinin indexini 1’den 10’a kadar olacak sekilde duzenleyin.
* Indexini duzenlediginiz seride, loc ve iloc metodlari ile, indexi 4,5,6 olan degerlere ulasin.
"""
seri1 = pd.Series([1,2,3,4,5])
seri2= pd.Series([6,7,8,9,10])
total = pd.concat([seri1,seri2])
total

0     1
1     2
2     3
3     4
4     5
0     6
1     7
2     8
3     9
4    10
dtype: int64

In [39]:
total.iloc[4:6]

4    5
0    6
dtype: int64

In [40]:
total.loc[4:6]

KeyError: 'Cannot get left slice bound for non-unique label: 4'

In [36]:
import numpy as np
import time 
### Master odev ;
"""
Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin. 
Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. Istenilen matris bulundugunda program dursun
 ve toplam kac dongunun kuruldugunu, ne kadar sure icinde buldugunu ve istenilen matrisi print ile birlikte ekrana yazdiriniz. 
#* Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi 
kucuk matrislerde deneyebilirsiniz. Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz. 
(Matris uretme islemini np.random.random((a,b)) fonksiyonu ile yapabilirsiniz. 0-1 arasi istenen boyutlarda array uretir.)
"""
start = time.time()
time.sleep(1)
counter = 0
while True :

    counter += 1
    matris1 = np.random.random((10,10))
    matris2 = np.random.random((10,10))
    m2m1 = matris2-matris1
    m1m2 = matris1-matris2

    counter1 = 0
    counter2 = 0
    for i in np.diag(m2m1): 
        if i < 0.1 and i > -0.1:
            counter1 += 1

    for j in np.diag(m1m2): 
        if j < 0.1 and j > -0.1:
            counter2 +=1
    if counter1 == 10 :
        print(m2m1)
        print("loop : ",counter)
        stop = time.time()
        print('second: ', stop-start)
        break
    elif counter2 == 10 :
        print(m1m2)
        print("loop : ",counter)
        stop= time.time()
        print('second: ', stop-start)
        break

            


    


[[ 9.29534125e-03 -5.97785151e-01  6.16364569e-02 -5.20763025e-02
  -8.52562575e-01  3.59002219e-01  5.12690301e-01 -5.50184760e-01
   6.55244923e-02 -4.64229813e-01]
 [-4.39130006e-01 -5.31995111e-02 -6.58236305e-01  1.53832033e-01
  -3.32439569e-01 -4.88831513e-02 -3.79208374e-01 -3.61765552e-01
  -1.25254126e-02 -2.09328400e-01]
 [ 3.04528841e-01  1.79991938e-01 -8.89090634e-02  4.98712217e-01
   4.25006061e-01  7.71860563e-02 -2.46480062e-03 -7.43682446e-01
   2.66542237e-01  1.72199291e-01]
 [-1.50527597e-01  6.90695875e-01 -5.48371135e-01 -1.83355329e-02
   5.04106467e-01  1.79151702e-01 -6.15398396e-01  4.86642392e-01
   7.91328116e-01  2.11269239e-01]
 [-6.54723530e-01 -5.97842189e-02 -6.25058730e-01  1.01930741e-02
  -5.09827970e-02 -3.52488821e-01  4.47526903e-01  1.82345430e-02
  -6.33448504e-02 -7.83157143e-01]
 [ 2.32883637e-01 -8.24321721e-01 -5.37680476e-01  3.67678599e-01
   1.07432934e-01  2.71341296e-02  1.22430682e-01 -3.16545075e-01
   2.91991572e-01  3.94720797e-01